# Generated by Django 2.1.4 on 2019-01-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mainpage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Color'),
        ),
    ]
