# Generated by Django 2.1.4 on 2019-01-02 14:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_textpage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='image_credit',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
