# Generated by Django 2.1.4 on 2019-01-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_color_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='blue',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='color',
            name='green',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='color',
            name='red',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
