# Generated by Django 2.1.4 on 2019-01-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
