# Generated by Django 2.1.4 on 2019-01-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectpagerelatedlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpagerelatedlink',
            old_name='link_external',
            new_name='url',
        ),
    ]
