# Generated by Django 2.1.4 on 2019-01-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectpagecollaboration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='body',
            new_name='teaser',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='body_de',
            new_name='teaser_de',
        ),
    ]
