# Generated by Django 2.1.4 on 2019-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectpage_body_body_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed')], default='IN_PROGRESS', max_length=32),
        ),
    ]
