# Generated by Django 2.1.4 on 2019-01-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogindexpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro_de',
        ),
    ]
