# Generated by Django 2.1.4 on 2019-01-10 09:39

from django.db import migrations
from wagtail.core.rich_text import RichText


def run_migration(apps, schema_editor):
    BlogPage = apps.get_model('blog', 'BlogPage')

    for page in BlogPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [('richtext', RichText(page.body.raw_text))]
            page.save()

        if page.body_de.raw_text and not page.body_de:
            page.body_de = [('richtext', RichText(page.body_de.raw_text))]
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_body_to_streamfield'),
    ]

    operations = [
        migrations.RunPython(run_migration),
    ]
